export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FINISH = 'FETCH_WEATHER_FINISH';
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';

export const SET_IS_INITIAL = 'SET_IS_INITIAL';
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const SET_IS_LOADING = 'SET_IS_LOADING';

export const SET_CITY_LIST = 'SET_CITY_LIST';


